name: json_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 🔹 JSON serialization package
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 🔹 Code generation tools
  build_runner: ^2.4.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
